name: sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # network_tools:
  dio: 4.0.4
  retrofit: 3.0.1
  json_serializable: 6.1.4

  riverpod: ^1.0.3
  go_router: ^4.2.9

  freezed_annotation: 1.1.0

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: 4.0.1
  build_runner: 2.1.7

  flutter_lints: ^2.0.0

  freezed: 1.1.1

  loggy: 2.0.1+1
  flutter_loggy: 2.0.1
  flutter_loggy_dio: 2.0.0+3

flutter:
  uses-material-design: true
